// <auto-generated />
using System;
using ChessSchool.ApiService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChessSchool.ApiService.Migrations.Arena
{
    [DbContext(typeof(ArenaDbContext))]
    [Migration("20260705175544_InitialArena")]
    partial class InitialArena
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChessSchool.ApiService.Domain.ArenaGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnalysisJson")
                        .HasColumnType("text");

                    b.Property<bool>("BlackIsBot")
                        .HasColumnType("boolean");

                    b.Property<string>("BlackName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BlackSub")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EndReason")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalGameId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pgn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Result")
                        .HasColumnType("integer");

                    b.Property<string>("TournamentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("WhiteIsBot")
                        .HasColumnType("boolean");

                    b.Property<string>("WhiteName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WhiteSub")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExternalGameId")
                        .IsUnique();

                    b.HasIndex("BlackSub", "PlayedAt");

                    b.HasIndex("WhiteSub", "PlayedAt");

                    b.ToTable("ArenaGames");
                });

            modelBuilder.Entity("ChessSchool.ApiService.Domain.ArenaGame", b =>
                {
                    b.OwnsOne("ChessSchool.Contracts.TimeControl", "TimeControl", b1 =>
                        {
                            b1.Property<Guid>("ArenaGameId")
                                .HasColumnType("uuid");

                            b1.Property<int>("IncrementSeconds")
                                .HasColumnType("integer");

                            b1.Property<int>("InitialSeconds")
                                .HasColumnType("integer");

                            b1.HasKey("ArenaGameId");

                            b1.ToTable("ArenaGames");

                            b1.WithOwner()
                                .HasForeignKey("ArenaGameId");
                        });

                    b.Navigation("TimeControl")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
