// <auto-generated />
using System;
using ChessSchool.ApiService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChessSchool.ApiService.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20260704083203_AddSchoolOwner")]
    partial class AddSchoolOwner
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ChessSchool.ApiService.Domain.ArenaGame", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AnalysisJson")
                        .HasColumnType("text");

                    b.Property<bool>("BlackIsBot")
                        .HasColumnType("boolean");

                    b.Property<string>("BlackName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BlackSub")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EndReason")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalGameId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Pgn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Result")
                        .HasColumnType("integer");

                    b.Property<string>("TournamentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("WhiteIsBot")
                        .HasColumnType("boolean");

                    b.Property<string>("WhiteName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WhiteSub")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExternalGameId")
                        .IsUnique();

                    b.HasIndex("BlackSub", "PlayedAt");

                    b.HasIndex("WhiteSub", "PlayedAt");

                    b.ToTable("ArenaGames");
                });

            modelBuilder.Entity("ChessSchool.ApiService.Domain.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ref")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("ChessSchool.ApiService.Domain.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BlackRatingChange")
                        .HasColumnType("integer");

                    b.Property<Guid?>("BlackStudentId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceRef")
                        .HasColumnType("text");

                    b.Property<int>("EndReason")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalGameId")
                        .HasColumnType("text");

                    b.Property<string>("Pgn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("PlayedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Result")
                        .HasColumnType("integer");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("WhiteRatingChange")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WhiteStudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BlackStudentId");

                    b.HasIndex("ExternalGameId")
                        .IsUnique();

                    b.HasIndex("WhiteStudentId");

                    b.HasIndex("Source", "PlayedAt");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("ChessSchool.ApiService.Domain.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("ChessSchool.ApiService.Domain.ProcessedBillingEvent", b =>
                {
                    b.Property<string>("EventId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("EventId");

                    b.ToTable("ProcessedBillingEvents");
                });

            modelBuilder.Entity("ChessSchool.ApiService.Domain.RatingPoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("RatingPoints");
                });

            modelBuilder.Entity("ChessSchool.ApiService.Domain.School", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerSub")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerSub");

                    b.ToTable("Schools");
                });

            modelBuilder.Entity("ChessSchool.ApiService.Domain.ShareLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("ShareLinks");
                });

            modelBuilder.Entity("ChessSchool.ApiService.Domain.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<bool>("ConsentGranted")
                        .HasColumnType("boolean");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Draws")
                        .HasColumnType("integer");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("LinkedUserSub")
                        .HasColumnType("text");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("RatingDeviation")
                        .HasColumnType("integer");

                    b.Property<double>("Volatility")
                        .HasColumnType("double precision");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("LinkedUserSub");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("ChessSchool.ApiService.Domain.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Plan")
                        .HasColumnType("text");

                    b.Property<string>("PriceId")
                        .HasColumnType("text");

                    b.Property<string>("ProviderCustomerId")
                        .HasColumnType("text");

                    b.Property<string>("ProviderSubscriptionId")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserSub")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProviderSubscriptionId");

                    b.HasIndex("UserSub")
                        .IsUnique();

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("ChessSchool.ApiService.Domain.ArenaGame", b =>
                {
                    b.OwnsOne("ChessSchool.Contracts.TimeControl", "TimeControl", b1 =>
                        {
                            b1.Property<Guid>("ArenaGameId")
                                .HasColumnType("uuid");

                            b1.Property<int>("IncrementSeconds")
                                .HasColumnType("integer");

                            b1.Property<int>("InitialSeconds")
                                .HasColumnType("integer");

                            b1.HasKey("ArenaGameId");

                            b1.ToTable("ArenaGames");

                            b1.WithOwner()
                                .HasForeignKey("ArenaGameId");
                        });

                    b.Navigation("TimeControl")
                        .IsRequired();
                });

            modelBuilder.Entity("ChessSchool.ApiService.Domain.Group", b =>
                {
                    b.HasOne("ChessSchool.ApiService.Domain.School", null)
                        .WithMany("Groups")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChessSchool.ApiService.Domain.Student", b =>
                {
                    b.HasOne("ChessSchool.ApiService.Domain.Group", null)
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ChessSchool.ApiService.Domain.Group", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("ChessSchool.ApiService.Domain.School", b =>
                {
                    b.Navigation("Groups");
                });
#pragma warning restore 612, 618
        }
    }
}
